### ISSUE TITLE
Feature: `to_list` missing from python async API

### ISSUE THREAD

**Issue by westonpace** [lancedb/lancedb#1515] opened 2024-08-07 15:52 UTC
### SDK

Python

### Description

The synchronous API had a `to_list` method that was a sibling to `to_arrow` and `to_pandas`.  The method simply did `to_arrow().to_pylist()` but could be helpful for people that are not familiar with arrow and just want to get python data directly.

It would be pretty easy to add back into the async API.

**Comment by wjones127** [comment] 2024-08-07 16:21
Closing as duplicate of #1517

**Closed by wjones127** 2024-08-07 16:21 UTC
Labels: enhancement, good first issue, help wanted
