### ISSUE TITLE
bug(python): Using a different vector_column_name for storing Vectors causes search() to fails

### ISSUE THREAD

**Issue by MadhavShroff** [lancedb/lancedb#1232] opened 2024-04-22 00:06 UTC
### LanceDB version

0.6.8

### What happened?

I created a local table but used a different name for the vectors, this caused the search() function to fail. Changing the name of the column to "vector" fixes this. 

### Are there known steps to reproduce?

On a M1 Pro MacBook Pro, lancedb's python package v0.6.8. 

Run the example at the bottom of the [README page](https://github.com/lancedb/lancedb/blob/main/README.md) as is, it works. 

Change the name of the "vector" field to something else like "emb", and in the search function, change table.search([100, 100]) to table.search([100, 100], vector_column_name="emb"), this breaks the code. 

Code that produces the error:

```python
import lancedb

uri = "data/sample-lancedb"
db = lancedb.connect(uri)
table = db.create_table("my_table",
                         data=[{"emb": [3.1, 4.1], "item": "foo", "price": 10.0},
                               {"emb": [5.9, 26.5], "item": "bar", "price": 20.0}])
result = table.search([100, 100], vector_column_name="emb").limit(2).to_pandas()
print(result)
``` 

Error Reported:
```
Traceback (most recent call last):
  File "/Users/lappy/Projects/lanceArxiv/wrong.py", line 8, in <module>
    result = table.search([100, 100], vector_column_name="emb").limit(2).to_pandas()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lappy/Projects/lanceArxiv/new_venv/lib/python3.12/site-packages/lancedb/query.py", line 262, in to_pandas
    tbl = self.to_arrow()
          ^^^^^^^^^^^^^^^
  File "/Users/lappy/Projects/lanceArxiv/new_venv/lib/python3.12/site-packages/lancedb/query.py", line 527, in to_arrow
    return self.to_batches().read_all()
           ^^^^^^^^^^^^^^^^^
  File "/Users/lappy/Projects/lanceArxiv/new_venv/lib/python3.12/site-packages/lancedb/query.py", line 557, in to_batches
    result_set = self._table._execute_query(query, batch_size)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lappy/Projects/lanceArxiv/new_venv/lib/python3.12/site-packages/lancedb/table.py", line 1606, in _execute_query
    return ds.scanner(
           ^^^^^^^^^^^
  File "/Users/lappy/Projects/lanceArxiv/new_venv/lib/python3.12/site-packages/lance/dataset.py", line 333, in scanner
    builder = builder.nearest(**nearest)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lappy/Projects/lanceArxiv/new_venv/lib/python3.12/site-packages/lance/dataset.py", line 2061, in nearest
    raise TypeError(
TypeError: Query column emb must be a vector. Got list<item: double>.
```

**Comment by raghavdixit99** [comment] 2024-04-22 00:43
This is an issue with how you are ingesting data, the issue mentions - `TypeError: Query column emb must be a vector. Got list<item: double>.`

I ran your code snippet and the schema is a simple list and not an pyarrow list.

You are trying to create a table using a custom schema w/o providing it ('vector' is the default vector field for implicit schema detection). Our [API reference](https://lancedb.github.io/lancedb/python/python/#lancedb.db.DBConnection.create_table )  mentions this :

 `Data is converted to Arrow before being written to disk. For maximum control over how data is saved, either provide the PyArrow schema to convert to or else provide a PyArrow Table directly.`

The below code runs fine, pls use this, additionally you can also ingest data via `LanceModel` , everything is mentioned in our API reference for development, we will be updating the docs once the team has bandwidth.

```python
import lancedb
import pyarrow as pa

custom_schema = pa.schema(
    [
        pa.field("emb", pa.list_(pa.float32(), 2)),
        pa.field("price", pa.float32()),
        pa.field("item", pa.string()),
    ]
)

uri = "./sample-lancedb"
db = lancedb.connect(uri)

table = db.create_table(
    "my_table",
    data=[
        {"emb": [3.1, 4.1], "item": "foo", "price": 10.0},
        {"emb": [5.9, 26.5], "item": "bar", "price": 20.0},
    ],
    schema=custom_schema,
)

result = table.search([100, 100]).limit(2).to_pandas()
print(result)
```

**Comment by raghavdixit99** [comment] 2024-04-22 00:46
closing this for now, its not a bug @changhiskhan  / @wjones127

**Closed by raghavdixit99** 2024-04-22 00:46 UTC
Labels: bug
