### ISSUE TITLE
bug(python): use_index still not available in LanceVectorQueryBuilder

### ISSUE THREAD

**Issue by kekulai-fredchang** [lancedb/lancedb#1618] opened 2024-09-07 13:17 UTC
### What happened?

Motivation: 

- Tuning IVFPQ ANN recall performance compared to exact KNN is a common workflow.  
- Therefore a use_index flag is necessary to switch the query from using an established index or not.  

Observations:
- Multiple `_indices` folders are create for each `create_index()` run.  
- If I move the '_indices' folder to force knn, I get `OSError: Io error: Execution error: LanceError(IO): Execution error: Not found: home/azureuser/localfiles/lancedb/bindingdb_espsim.lance/_indices/c0228cef-e2a8-45d8-9175-8bb331cb4917/index.idx, /home/runner/work/lance/lance/rust/lance-io/src/local.rs:99:31, /home/runner/work/lance/lance/rust/lance/src/io/exec/take.rs:64:42`.   A better default in `local.rs` is to revert back to knn.  

Feature Request:
- revisit commit f9ccefb0320574 to incorporate use_index and even better, to switch between indexes, e.g. use_index([True, False,or "c0228cef"]).

**Comment by wjones127** [comment] 2024-09-09 22:53
Hi @kekulai-fredchang, this seems like a duplicate of #535.

Also, I think this was actually implemented partially as a `bypass_vector_index()` method in https://github.com/lancedb/lancedb/pull/1113. It is, however, missing from the docs. I will update the original issue.

**Closed by wjones127** 2024-09-09 22:53 UTC
Labels: bug
