### ISSUE TITLE
Feature: Support search by distance threshold

### ISSUE THREAD

**Issue by bw-matthew** [lancedb/lancedb#1369] opened 2024-06-08 13:42 UTC
### SDK

Python

### Description

Instead of only limiting the search by top-k the search could be limited by a distance threshold. This is consistent with the Voronoi cell approach as you can enumerate the cells that are within a given distance of the cell that contains the search point (you need to consider that the search point can be anywhere in the cell and adjust the distance accordingly).

This would allow the database to be used in more flexible ways, e.g:

* for document clustering where you want to find all points within some threshold distance of a given point (like in DBSCAN)
* for maintaining a database of _queries_ and matching a stream of incoming documents to all queries that are within the distance threshold

**Comment by wjones127** [comment] 2024-06-11 17:59
Thanks, this is a good idea. I think this is a duplicate of #745, so I'm closing it in favor of that one.

**Closed by wjones127** 2024-06-11 17:59 UTC
Labels: enhancement

**Comment by wjones127** [comment] 2024-06-15 04:44
> The distinction here is that I would desire no limit at all.

You are always welcome to set the limit to like a billion. No limit means no bound on latency, which I think should be explicitly opt in.
