### ISSUE TITLE
Feature: Please add support for windows arm machines (creation of @lancedb/lancedb-win32-arm64-msvc package)

### ISSUE THREAD

**Issue by FominArtmind** [lancedb/lancedb#1841] opened 2024-11-18 04:59 UTC
### SDK

Node

### Description

It would be great to add arm64 support for nodejs like is has been recently done for Python version: https://github.com/lancedb/lancedb/pull/1770.

LanceDB compilation guide doesn't provide information on how to build on windows so I suppose it's impossible to build for win32-arm64 at the point.

**Comment by wjones127** [comment] 2024-11-18 16:43
That PR you linked was intended to build on Windows arm for Node, not Python, actually. I had to disable it because it didn't 100% work.

I have the beginnings of a fix here: https://github.com/lancedb/lancedb/pull/1831
But I don't have time to work on it. If you or someone else wants to finish that PR and get it working, I'm happy to merge that.

Regardless, once we have that release CI job fixed, I would appreciate your help testing it. I don't have a Windows Arm64 machine.

**Comment by FominArtmind** [comment] 2024-11-18 17:06
I also don't possess such a machine to make any actual builds on it. I have an electron app using lancedb that is configured to create builds for both win x64 / win arm64 and x64 build works fine on my machine. As for arm64 build I have a remote colleague who runs it and tells me about the results, now the build is at the point where UI works fine but lancedb initialization fails due to absence of a proper prebuilt version. I will be happy to ask the colleague to run the app with any new version of lancedb package and report you back but as for creation of a PR I think I'm so low in my understanding of the required things that it will take me enormous time to get into it.

**Comment by wjones127** [comment] 2024-11-18 17:40
> as for creation of a PR I think I'm so low in my understanding of the required things that it will take me enormous time to get into it

That's fine, we'll let someone else take a look at it.

**Comment by svantesorberg** [comment] 2024-11-19 20:19
I can take a crack at this. Stumbled across lancedb as a dependency in [another project](https://github.com/continuedev/continue/issues/839) I was interested in running on my arm64 windows laptop (Snapdragon X Elite). I built it both directly on an arm64 machine and cross-compiled from win-amd64 so I have some confidence that it's at least _possible_. Quite busy these upcoming days though so if someone else wants to apply themselves in the meantime I'd be happy to cheer from the sidelines and help out here in the thread.

**Comment by svantesorberg** [comment] 2024-11-28 11:26
I see there is a PR up now for windows arm64 using cross-compilation from alpine. Is there a preference for native- or cross-compilation in the project? I was just starting to debug my native arm build.

https://github.com/lancedb/lancedb/pull/1890

**Comment by wjones127** [comment] 2024-12-06 20:37
This was just released in v0.14.0.

Please try it out and let if know if you encounter any issues.

**Closed by wjones127** 2024-12-06 20:37 UTC
Labels: enhancement, help wanted

**Comment by FominArtmind** [comment] 2024-12-11 18:27
> This was just released in v0.14.0.
> 
> Please try it out and let if know if you encounter any issues.

Could you please clarify how it can be installed properly?
To make lanceDB work in Node environment, I need not one but two packages:
    "@lancedb/lancedb": "^0.14.0",
    "@lancedb/lancedb-win32-x64-msvc": "^0.14.0"
The last one is available.
However, to run on win arm, there is a need in something like @lance/lancedb-win32-arm64-msvc and looks like that there is no such prebuilt package.
