### ISSUE TITLE
bug(python): Failed to get AWS credentials: the credentials provider was not properly configured

### ISSUE THREAD

**Issue by ben-elsen** [lancedb/lancedb#1446] opened 2024-07-16 07:43 UTC
### LanceDB version

v0.10.0

### What happened?

I am trying to getting started with lanceDB and AWS S3 but I am getting this error:
`OSError: LanceError(IO): Generic N/A error: Encountered internal error. Please file a bug report at https://github.com/lancedb/lance/issues. Failed to get AWS credentials: the credentials provider was not properly configured, /Users/runner/work/lance/lance/rust/lance-io/src/object_store.rs:170:31, /Users/runner/work/lance/lance/rust/lance-table/src/io/commit.rs:104:26`

My AWS credentials are correctly configured, I verified this with aws sts get-caller-identity and other scripts.

The debugging output is: 
```
 RUST_LOG=debug LANCE_LOG=debug AWS_DEFAULT_REGION=us-east-1 python ../../../../../../Downloads/test_lance_db.py
[2024-07-15T12:10:47Z DEBUG reqwest::connect] starting new connection: https://van-roey-workshop-03062024.s3.amazonaws.com/
[2024-07-15T12:10:47Z DEBUG rustls::client::hs] No cached session for DnsName("van-roey-workshop-03062024.s3.amazonaws.com")
[2024-07-15T12:10:47Z DEBUG rustls::client::hs] Not resuming any session
[2024-07-15T12:10:48Z DEBUG rustls::client::hs] Using ciphersuite TLS13_AES_128_GCM_SHA256
[2024-07-15T12:10:48Z DEBUG rustls::client::tls13] Not resuming
[2024-07-15T12:10:48Z DEBUG rustls::client::tls13] TLS1.3 encrypted extensions: [ServerNameAck, Protocols([ProtocolName(687474702f312e31)])]
[2024-07-15T12:10:48Z DEBUG rustls::client::hs] ALPN protocol is Some(b"http/1.1")
[2024-07-15T12:10:48Z DEBUG rustls::common_state] Sending warning alert CloseNotify
[2024-07-15T12:10:48Z DEBUG hyper_rustls::config] with_native_roots processed 165 valid and 0 invalid certs
Traceback (most recent call last):
  File "/Users/benelsen/Documents/Engineering/Spectrum/Customers/Van Roey/vanroey-chatbot-poc/../../../../../../Downloads/test_lance_db.py", line 19, in <module>
    tbl = db.create_table("test", schema=DocumentModel, mode="create")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/benelsen/.virtualenvs/van_roey_poc/lib/python3.12/site-packages/lancedb/db.py", line 417, in create_table
    tbl = LanceTable.create(
          ^^^^^^^^^^^^^^^^^^
  File "/Users/benelsen/.virtualenvs/van_roey_poc/lib/python3.12/site-packages/lancedb/table.py", line 1577, in create
    lance.write_dataset(empty, tbl._dataset_uri, schema=schema, mode=mode)
  File "/Users/benelsen/.virtualenvs/van_roey_poc/lib/python3.12/site-packages/lance/dataset.py", line 2568, in write_dataset
    inner_ds = _write_dataset(reader, uri, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: LanceError(IO): Generic N/A error: Encountered internal error. Please file a bug report at https://github.com/lancedb/lance/issues. Failed to get AWS credentials: the credentials provider was not properly configured, /Users/runner/work/lance/lance/rust/lance-io/src/object_store.rs:170:31, /Users/runner/work/lance/lance/rust/lance-table/src/io/commit.rs:104:26
```

### Are there known steps to reproduce?

My script is: 
```
import os

import lancedb
import pandas as pd
from lancedb.embeddings import get_registry
from lancedb.pydantic import LanceModel, Vector

os.environ["AWS_DEFAULT_REGION"] = "us-esat-1"

uri = "s3://workshop-03062024/sample-lancedb/embeddings"

db = lancedb.connect(uri)
model = get_registry().get("bedrock-text").create()

class DocumentModel(LanceModel):
    text: str = model.SourceField()
    vector: Vector(model.ndims()) = model.VectorField()

tbl = db.create_table("test", schema=DocumentModel)
df = pd.DataFrame()

for file_name in FILES_IN_SCOPE:
    for item in FileModel.file_by_name_index.query(file_name):
        df.add({"text": item.raw_content})
        print(f"Added {item.file_name}")


tbl.add(df)
rs = tbl.search("hello").limit(1).to_pandas()
```

**Comment by wjones127** [comment] 2024-07-16 20:27
"the credentials provider was not properly configured" comes directly from the `aws_config` crate from AWS Rust SDK. So it's according to them that it's not configured correctly. Could you share how you were configuring it? Which environment variables and settings you were using? Also can you verify other AWS tools, like the AWS CLI work with your credentials?

**Comment by ben-elsen** [comment] 2024-07-16 20:33
hi @wjones127 I use the 'AWS_PROFILE' env var for my AWS authentication. The cli works, I validated it with: `aws sts get-caller-identity`

**Comment by wjones127** [comment] 2024-07-16 20:36
Which keys are filled in within your AWS_PROFILE entry?

**Comment by ben-elsen** [comment] 2024-07-16 20:38
I have: 
```
[profile AWSPowerUserAccess-456351737712]
sso_session = spectrum_default
sso_account_id = 456351737712
sso_role_name = AWSAdministratorAccess
region = us-east-1
output = json
```

**Comment by wjones127** [comment] 2024-07-18 18:15
Okay, I'm able to reproduce this. Odd, since this used to work. I'll look into how we can fix this soon. In the meantime, I suggest you get concrete credentials for now (`aws_access_key_id` and so on)

https://github.com/lancedb/lance/issues/2614

**Comment by wjones127** [comment] 2024-07-18 19:47
We'll have a fix for this soon when we upgrade the Lance library in LanceDB. :)

**Comment by ben-elsen** [comment] 2024-07-18 20:21
Awesome! Any idea when that upgrade would take place? :-)

**Comment by wjones127** [comment] 2024-07-18 20:30
Sometime in the next week, I expect.

**Closed** 2024-07-26 16:13 UTC
Labels: bug
