### ISSUE TITLE
bug(python): lancedb saved torch device and it isn't easily mutable

### ISSUE THREAD

**Issue by PhorstenkampFuzzy** [lancedb/lancedb#1958] opened 2024-12-18 19:08 UTC
### What happened?

Currently when adding an embedding over the lancedb registry we are not capable of overwriting / changing the device name. This make the use of lancedb much more difficult than needed. The same is for a lesser extend true for the model name but easier to workaround.

I had a hardware breakdown. Since for read only use cpu isn't that big of a problem we wanted to switch but couldn't.

### Are there known steps to reproduce?

Create a table with a vector with GPU as a device. Change the device to CPU / execute on a CPU only docker container and the system will not be able to load.

**Comment by wjones127** [comment] 2024-12-18 19:35
Thanks for reporting this @PhorstenkampFuzzy. We are already tracking this issue in #1958

I'm going to close this as a duplicate of #1958

**Closed by wjones127** 2024-12-18 19:35 UTC
Labels: bug

**Comment by PhorstenkampFuzzy** [comment] 2024-12-18 23:24
Could you give me the actual number? The issue you cited is this issue.

**Comment by wjones127** [comment] 2024-12-19 00:30
> Could you give me the actual number? The issue you cited is this issue.

Sorry about that. Updated.

Duplicate of #521
