### ISSUE TITLE
bug(python): operations failing when running against GCS

### ISSUE THREAD

**Issue by fekstr** [lancedb/lancedb#1001] opened 2024-02-19 22:18 UTC
### LanceDB version

v0.5.5

### What happened?

- `table_names` returns an empty list even though there are tables
- `drop_table` successfully drops the table and then throws a `FileNotFoundError`

### Are there known steps to reproduce?

```python
db = lancedb.connect(f"gs://bucket-name")
db.create_table("table", data=[{"id": 1}])
print(db.table_names()) # []
db.drop_table("table") # google::cloud::Status(NOT_FOUND: Permanent error DeleteObject: No such object: ...
```

**Comment by wjones127** [comment] 2024-02-19 22:22
Hi @fekstr. I believe this is a duplicate of https://github.com/lancedb/lancedb/issues/673

We are working toward a fix, but will take some time to implement.

**Comment by fekstr** [comment] 2024-02-19 22:29
Seems like the first issue is a duplicate. The failure to drop tables is not the same but perhaps related. Feel free to close this if they will be closed by the same fix.

**Comment by wjones127** [comment] 2024-02-19 22:46
Yes, it should be fixed by the same changes.

**Closed by wjones127** 2024-02-19 22:46 UTC
Labels: bug
