### ISSUE TITLE
bug(python): Hybrid search with zero fts search results returns inconsistent dataframe 

### ISSUE THREAD

**Issue by marketneutral** [lancedb/lancedb#1675] opened 2024-09-20 14:25 UTC
### LanceDB version

v0.13

### What happened?

In the case of hybrid search, the vector search and fts search results are merged and a combined '_relavance_score' is returned. However, in the case where the search resulted in no fts results, the hybrid search returns only the dataframe for the vector results without a `_relevance_score`. This makes it difficult for downstream code to use the results of hybrid search because the return dataframes are inconsistent depending on the search outcome. The return dataframes should contain consistent columns regardless of the results of the search.

**Comment by AyushExel** [comment] 2024-09-20 14:26
Thanks for reporting. I'm looking into it.

**Comment by AyushExel** [comment] 2024-09-20 14:31
@marketneutral I'm not able to reproduce.. Here you can see the FTS result is empty but hybrid search still returns _relevance_metric
<img width="815" alt="Screenshot 2024-09-20 at 8 01 10 PM" src="https://github.com/user-attachments/assets/48bc6d2f-06b3-496f-a806-d79036d66fba">

**Comment by AyushExel** [comment] 2024-09-20 15:03
@marketneutral You might want to upgrade lancedb with `pip install --upgrade lancedb`. I think the problem that you're seeing is in [LinearCombinationReranker](https://github.com/lancedb/lancedb/blob/main/python/python/lancedb/rerankers/linear_combination.py#L64) which was default  before and has been replaced by RRFReranker. I'll update the handling of LinearCombinationReranker so that it always returns the _relevance_score

**Comment by AyushExel** [comment] 2024-09-20 16:10
Awesome! Closing this one. I've made a note of this in the hybrid sarch epic

**Closed by AyushExel** 2024-09-20 16:10 UTC
Labels: bug
